[versions]
# CORE BUILD PLUGINS
agp = "8.13.2"

# DEPENDENCIES
appcompat = "1.7.1"
activity = "1.12.2"
#noinspection GradleDependency
fragment = "1.8.2"
constraintlayout = "2.2.1"
material = "1.13.0"
#noinspection GradleDependency,GradleDependency,GradleDependency,GradleDependency
lifecycle = "2.8.4"
#noinspection GradleDependency,GradleDependency,GradleDependency
room = "2.6.1"
annotation = "1.9.1"
bcrypt = "0.10.2"

# TESTING
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

[libraries]
# ANDROIDX
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }

# LIFECYCLE
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }

# ROOM
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-rxjava3 = { group = "androidx.room", name = "room-rxjava3", version.ref = "room" }

# OTHER
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt" }

# TESTING
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
